### PR TITLE
allow custom grouping for user recipes

### PR DESCRIPTION
**Pull request by piever**
See [#1062](https://github.com/JuliaPlots/Plots.jl/pull/1062)

### CODE REVIEW

**Comment by mkborregaard** [comment]
If we do choose to merge this, https://github.com/JuliaPlots/StatPlots.jl/pull/83/files and https://github.com/JuliaPlots/Plots.jl/pull/1062 , it should probably be in connection with the bump to julia 0.7.

**Comment by piever** [comment]
Any hint as to when that would be more or less? But I agree that this is part of a largish set of changes as, if this gets merged, also `groupapply` can be simplified quite a bit, in the current version I had to do the `groupedbar` by hand.

**Comment by mkborregaard** [comment]
5-6 months? The thing is we only align new releases of RecipesBase that create downstream changes with julia major releases. In that way we can attach Plots and friends to the new version too and prevent version conflicts - part of what makes RecipesBase a safe dependency. If we need to, we could have a julia-0.7 branch of RecipesBase and Plots that stays rebased on master and has the functionality.

**Comment by mkborregaard** [comment]
Cool. We could leave it open, or reopen it later once we bump the version.

**Comment by piever** [comment]
Yep, I'll reopen when we bump versions.

**Pull request closed without merging**
