### PR TITLE
Add test cases for #22

### PR DESCRIPTION
**Pull request by iblis17**
- update README, using `struct` in julia 0.6+

---

Once #22 get merged, I will rebase this PR.

### CODE REVIEW

**Comment by iblis17** [comment]
rebased

**Comment by iblis17** [comment]
Thanks!

good to tag a new release now?

**Comment by daschw** [comment]
Will do tomorrow, have to go now.

**Comment by mkborregaard** [comment]
With RecipesBase being so fundamental to many packages, and so rarely updated, I'd really prefer this to be field-tested by those on master for a few weeks before pushing a new release. @iblis17 , do you have a class or some other particular reason for having this in a released version, rather than just staying on master for a little while?

**Comment by iblis17** [comment]
👌 , I can wait.

> do you have a class or some other particular reason for having this in a released version, rather than just staying on master for a little while?

No, I just love new feature :)

**Pull request merged**
