### PR TITLE
Fix "-->" by distinguishing explicit and default attributes.

### PR DESCRIPTION
**Pull request by yha**
Dict type with explicit and default attributes imlpemented in a separate `Plots.jl` PR.

### CODE REVIEW

**Comment by mkborregaard** [comment]
@yha this seems to have caused breakage downstream in recipes - like for GraphRecipes https://github.com/JuliaPlots/GraphRecipes.jl/pull/95 and https://github.com/JuliaPlots/GraphRecipes.jl/issues/93 and my guess would be a lot of other recipes down the line as well. Should we revert this update, or do you think you could work out what's happened downstream?

cc @daschw @asinghvi17

**Comment by daschw** [comment]
I don't think that RecipesBase is the problem. The changes here don't seem breaking. The issue is rather in Plots.jl. https://github.com/JuliaPlots/Plots.jl/pull/2388 should provide some fixes.

**Comment by mkborregaard** [comment]
That's awesome - so all we need is to tag a new version?

**Comment by daschw** [comment]
I hope so, not sure if other fixes in Plots are required. I'll test GraphRecipes soon

**Comment by yha** [comment]
> The issue is rather in Plots.jl. [JuliaPlots/Plots.jl#2388](https://github.com/JuliaPlots/Plots.jl/pull/2388) should provide some fixes.

Thanks for cleaning up my mess!
I suppose we need an example with `link` for testing, and also to run tests of some downstream recipes packages when making such changes.
In my machine, with `Plots` master and `RecipesBase` 0.8, I see `GraphRecipes` tests pass, and `StatsPlots` fail due to missing `Test` package (JuliaPlots/StatsPlots.jl#257?). But both package seem to be forced to a previous version by the `RecipesBase` update.

**Comment by daschw** [comment]
> Thanks for cleaning up my mess!

Don't worry! We all make mistakes. I could have reviewed more carefully, too.

**Pull request merged**
